# permissions for end users to edit sqlgrants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqlgrants-editor-role
rules:
- apiGroups:
  - stenic.io
  resources:
  - sqlgrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stenic.io
  resources:
  - sqlgrants/status
  verbs:
  - get
