# permissions for end users to edit sqlusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqluser-editor-role
rules:
- apiGroups:
  - stenic.io
  resources:
  - sqlusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stenic.io
  resources:
  - sqlusers/status
  verbs:
  - get
